# host: _allday_dev_server
env: 'dev'
aws_region: "ap-south-1"
aws_target_group: "oppvenuz-dev-api-tg"
service_container_name: "oppvenuz-dev-api"
nginx_container_published_port: "8080"
host_container_published_port: "9000"