host: _allday_dev_server
env: 'uat'
aws_region: "ap-south-1"
aws_target_group: "oppvenuz-uat-api-tg"
service_container_name: "oppvenuz-uat-api"
nginx_container_published_port: "8080"
host_container_published_port: "8000"
